---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: edge-microgateway
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: edge-microgateway
        app: edge-microgateway
    spec:
      containers:
        - name: edge-microgateway
          image: gcr.io/YOUR_PROJECT_ID/microgateway-4k:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8000
          resources:
            limits:
              cpu: "3"
              memory: "1024M"
            requests:
              cpu: "3"
              memory: "1024M"
          env:
            - name: EDGEMICRO_ORG
              valueFrom:
                secretKeyRef:
                  name: mgwsecret
                  key: mgorg
            - name: EDGEMICRO_ENV
              valueFrom:
                secretKeyRef:
                  name: mgwsecret
                  key: mgenv
            - name: EDGEMICRO_KEY
              valueFrom:
                secretKeyRef:
                  name: mgwsecret
                  key: mgkey
            - name: EDGEMICRO_SECRET
              valueFrom:
                secretKeyRef:
                  name: mgwsecret
                  key: mgsecret
            - name: EDGEMICRO_CONFIG_DIR
              value: "/home/microgateway/.edgemicro"
            - name: EDGEMICRO_PROCESSES
              value: "3"
---
