apiVersion: v1
kind: Pod
metadata:
  name: nodejs-backend
  labels:
    app: nodejs-backend
spec:
  restartPolicy: Always
  containers:
    - name: nodejs-backend
      image: gcr.io/YOUR_PROJECT_ID_HERE/nodejs-backend:latest
      ports:
        - containerPort: 8080

---
