apiVersion: v1
kind: Service
metadata:
  name: nodejs-backend
  labels:
    app: nodejs-backend
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: nodejs-backend
  type: LoadBalancer
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nodejs-backend
spec:
  replicas: 1
  selector:
    app: nodejs-backend
  template:
    metadata:
      name: nodejs-backend
      labels:
        app: nodejs-backend
    spec:
      containers:
      - name: nodejs-backend
        image: gcr.io/YOUR_PROJECT_ID_HERE/nodejs-backend:latest
        ports:
        - containerPort: 8080
---
